### ISSUE TITLE
Just to be contributor

### ISSUE THREAD

**Issue by ibrahimcimentepe** [kyzn/inspireMe#1]
..

**Comment by kyzn** [comment]
I guess you still have to commit something. Try editing readme file.
Also, we should talk about moving to meteor.. on another issue

**Comment by ibrahimcimentepe** [comment]
About meteor, I had seen that Meteor has no "official" support on windows.. Therefore I thought it is unapplicable for me..
But there seems to be some unofficial solutions, (http://win.meteor.com/) I will return after checking them. And also php case either..

**Comment by kyzn** [comment]
There's xampp for php in windows, can you check that too?

**Comment by ibrahimcimentepe** [comment]
Yep. I will try to return on this issue until Saturday 01:00 am. See you later.

**Comment by ibrahimcimentepe** [comment]
Still working on Meteor, nothing to report yet. 
For the xampp case, I used that in internship, and found some tutorials to try and see what I can do..

All in all, I will return ASAP with results and suggestions, hopefully till Saturday dawn.
