### ISSUE TITLE
Pre-approve members to a community

### ISSUE THREAD

**Issue by ibrahimcimentepe** [kyzn/inspireMe#12]
1.    available only for users (guests will be redirected into index)
2.    available only for admins of given community (users will be redirected into show_community.php?comm_id=123)
3.    list outstanding requests > approve / reject
4.    when a request is approved show_requests_approve.php?comm_id=123&user_id=123 will be called
5.    when a request is deleted show_requests_delete.php?comm_id=123&user_id=123 will be called

**Comment by kyzn** [comment]
All above works fine. We will implement a "invitation - pre-approve" type of add as well (which we discussed at lecture)
