### ISSUE TITLE
Profile Information

### ISSUE THREAD

**Issue by ibrahimcimentepe** [kyzn/inspireMe#13]
- Basic User Info : Joined Time, Last Activity Time, Real Name(?)
- Contact Information : Email Address, Facebook adress(?), Twitter address(?)
- Activity : Total Post Count, Total Comment Count, Total Likes (Upvotes), Follower Count(?), Share Count(?)
- Enrolled Communities
- Recent Activity : Posted, commented, liked (post or comment), followed (person), shared etc..

**Comment by kyzn** [comment]
- We don't store "last login"
- We can add real name (full name?), it was in another issue
- Showing e-mail addresses publicly might not be a good idea. Some users don't prefer their addresses to be shown.
- Post count, comment count, upvote count are plausible. Following is discussed in another issue and I don't recall discussing on follow relations. It'd be nice if you can elaborate on that. Share count is not possible at the moment, please drop it.
- If User-id is not passed (?user_id=1) it should show logged in users profile (it does not)

**Comment by ibrahimcimentepe** [comment]
If User-id is not passed (?user_id=1) it should show logged in users profile (it does not) : Condition added.

**Comment by ibrahimcimentepe** [comment]
Post Tags segment has been implemented. Need other button for other users to submit tags, also db is not suitable for this operation.

**Comment by ibrahimcimentepe** [comment]
Contact info has been marked by Suzan Hoca as must-be. Let's open another minor issue to enable user to make private this info.

**Comment by kyzn** [comment]
should we close this one?
