### ISSUE TITLE
Latest posts segment in post page

### ISSUE THREAD

**Issue by ibrahimcimentepe** [kyzn/inspireMe#17]

**Comment by kyzn** [comment]
Is this necessary? I recall getting feedback adding too many things to right column could be very distractive for show_post.php

**Comment by ibrahimcimentepe** [comment]
Easy to implement. Also, we do not have so much visual in post page, At center; Description and Comment, At right, latest post and categories exists. 

Tagging was not fully implemented at the time of the comment, lets talk after redesign, I will inform you here.

**Comment by ibrahimcimentepe** [comment]
Completed.
