### ISSUE TITLE
Additional information from users

### ISSUE THREAD

**Issue by ibrahimcimentepe** [kyzn/inspireMe#20]
Profile Picture, Facebook, Twitter, Real name, age (demographic), Occupation

**Comment by kyzn** [comment]
Can you explain more on this issue? I don't recall discussing none of above.
> Adding profile picture (uploading etc.) requires some implementation, do we really need that? When did we talk on this one?
> Is Twitter-Facebook connect really needed, if that's what you meant?

**Comment by kyzn** [comment]
- Full name, birth date, occupation can be added to database. User will enter these information upon registering.
- Do we really need profile picture, facebook connect, and twitter connect? I don't recall discussing on that.
