### ISSUE TITLE
Featured Community page

### ISSUE THREAD

**Issue by ibrahimcimentepe** [kyzn/inspireMe#5]
At the main page, there will be an example community page to attract new users on using our system.
- Bring one random public community, print description etc.

**Comment by kyzn** [comment]
Does this work properly? Please comment.

**Comment by ibrahimcimentepe** [comment]
No, not at the moment. Currently, there is a sample_community, which I will replace it with random public community. To do that, displaying public community would be open for non-user client. I recall that is not the case right now.

Nevertheless, I will write the code and when this ability is open, we can comment sample_community line. I am going to open another issue for this ability.

**Comment by kyzn** [comment]
reporting as future work
