### ISSUE TITLE
Implementation of Profile Page

### ISSUE THREAD

**Issue by ibrahimcimentepe** [kyzn/inspireMe#7]
1.    available only for users (guests will be redirected into index)
2.    if id is not given, show logged user's profile (ie. redirect to show_user.php?user_id=$_SESSION['UserID'] 
3.    show user's information
4.    show communities user belong to
5.    show posts
6.    show total post count, comment count, number of post upvotes received, number of comment upvotes received **(gamification)**

**Comment by kyzn** [comment]
Same with #13
