### ISSUE TITLE
Sorting posts of a community

### ISSUE THREAD

**Issue by ibrahimcimentepe** [kyzn/inspireMe#9]
1.    available only for users (guests will be redirected into index)
2.    if it's a private community, we'll check whether user is already in the community. if not, posts will be hidden.
3.    public > join button (unless already joined)
4.    private > request to join button (unless already joined OR sent a join request)
5.    details of a given community (shortdescription, createdon)
6.    posts in community (title, text, upvote button, links to each show_post.php)
7.       sort posts: reverse chronological order
8.       sort posts: use an algorithm similar to 9gag (later)

**Comment by ibrahimcimentepe** [comment]
Community page : List of posts and associated users. Posts might be extended with more information and mini post pages.

**Comment by kyzn** [comment]
- In all above, the only thing missing is "sorting", which I'll take care of.
- As I said in #15, I don't understand what a mini post is.
